version: '3'
services:
  frontend:
    environment:
      - API_URL=http://backend:8000/
      - API_URL_BROWSER=/
    container_name: frontend
    build:
      context: ./frontend
      args:
        static_build: 0
    command: npm run dev
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5000:5000
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000