# Generated by Django 2.2.1 on 2019-05-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='name',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
