# Generated by Django 2.2.1 on 2019-05-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_auto_20190524_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
